// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC47Ex7yoj03oz0jnvrRKhEkXWKWYHMdmU',
    appId: '1:708946335331:web:8d568c63958208ccabca56',
    messagingSenderId: '708946335331',
    projectId: 'simola-2f527',
    authDomain: 'simola-2f527.firebaseapp.com',
    storageBucket: 'simola-2f527.firebasestorage.app',
    measurementId: 'G-T6J1FL61P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8oviNW-xXv9RkczbBpliXXpNG2ZmRPqA',
    appId: '1:708946335331:android:c6b6ff5e9ce9b501abca56',
    messagingSenderId: '708946335331',
    projectId: 'simola-2f527',
    storageBucket: 'simola-2f527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmEJGiMS6w6rk9qPbsZJTNBz5ZjaUppWc',
    appId: '1:708946335331:ios:a596fe6a919ca00eabca56',
    messagingSenderId: '708946335331',
    projectId: 'simola-2f527',
    storageBucket: 'simola-2f527.firebasestorage.app',
    iosBundleId: 'com.example.simola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmEJGiMS6w6rk9qPbsZJTNBz5ZjaUppWc',
    appId: '1:708946335331:ios:a596fe6a919ca00eabca56',
    messagingSenderId: '708946335331',
    projectId: 'simola-2f527',
    storageBucket: 'simola-2f527.firebasestorage.app',
    iosBundleId: 'com.example.simola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC47Ex7yoj03oz0jnvrRKhEkXWKWYHMdmU',
    appId: '1:708946335331:web:6852a0e4d33fbdacabca56',
    messagingSenderId: '708946335331',
    projectId: 'simola-2f527',
    authDomain: 'simola-2f527.firebaseapp.com',
    storageBucket: 'simola-2f527.firebasestorage.app',
    measurementId: 'G-WWBZ02R417',
  );
}
